name: Build

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g., for dependabot pull requests)
  push:
    branches: [ main ]

  # Trigger the workflow on any pull request
  pull_request:

  # Trigger the workflow when called by another workflow
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || null }}
          # fetch all reachable commits, not just one (commit history required for MinVer version inference)
          fetch-depth: 0
          # only fetch required blobs and trees; fetch others as needed
          filter: tree:0
          submodules: recursive

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9"

      - name: Restore solution
        run: |
          dotnet restore -c Release

      - name: Build solution
        run: |
          dotnet build -c Release

      - name: Pack solution
        run: |
          dotnet pack -c Release --no-build

      - name: Upload nupkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg-build
          path: ./*/bin/Release/*.nupkg
